language: julia
os:
    - linux
julia:
    - 1.3
    - 1
    - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
    email: false
after_success:
    # push coverage results to Codecov
    - julia -e 'cd(Pkg.dir("RDKafka")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'